### ISSUE TITLE
Support Fixed Interval Sensor Without a Linked Device

### ISSUE THREAD

**Issue by rafael-zilberman** [rafael-zilberman/device-maintenance-monitor-custom-component#12]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/rafael-zilberman/device-maintenance-monitor-custom-component/labels/enhancement).

### Is your feature request related to a problem? Please describe.

There is a need for fixed interval reminders for tasks that do not involve a specific device, similar to the virtual sensor in PowerCalc.

### Describe the solution you'd like

Create a fixed interval sensor that operates independently of any linked device. This sensor would provide reminders based on a set time interval.

### Additional context

This feature would be useful for general maintenance tasks, such as changing batteries, that do not have a specific device associated with them.

**Comment by wormiedk** [comment]
I concur. It would be great for tracking descaling of faucets and other maintenance tasks on non connected appliances.
