### ISSUE TITLE
Define the inital value for "last maintenance" for new devices

### ISSUE THREAD

**Issue by FrankGiesecke** [rafael-zilberman/device-maintenance-monitor-custom-component#38]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/rafael-zilberman/device-maintenance-monitor-custom-component/labels/enhancement).

### Is your feature request related to a problem? Please describe.

I'm new with this integration and started to add entities.

For fixed intervals, I'd like to set the date of the last maintenance. After adding a new device, the date of the last maintenance ore runs etc. are set to today or 0. So I used the developer tools to adjust the `sensor.xxx_predicted_maintenance_date` value and the `binary_sensor.xxx_maintenance_needed` attributes. But after some seconds, the values are reseted to the former information (today, 0).

### Describe the solution you'd like

I need some service or an optional input to set the initial value.

### Describe alternatives you've considered

-

### Additional context

Mostly, users have already maintained, running devices when installing this great helper. So it is necessary to set the initial information if they are known.

**Comment by rafael-zilberman** [comment]
Thanks for the suggestion! I will keep you updated about the development of this feature

**Comment by rafael-zilberman** [comment]
Hey, 
Please see #43 which released in version 0.2.0, this should address your request :)

**Comment by FrankGiesecke** [comment]
@rafael-zilberman Thanks for the fast implementaion. It works great 🙏
